### ISSUE TITLE
Non standard Node executable path or name was: Unable to start nodeclipse on ubuntu 14

### ISSUE THREAD

**Issue by broadbear** [Nodeclipse/nodeclipse-1#158]
After a new installation of eclipse/nodeclipse plugin on ubuntu 14, I was unable to restart eclipse. I see the below error in .log. It looks like the binary name is hard coded in the PreferenceInitializer class as 'node', however, on ubuntu there is a package name conflict, so the binary is named 'nodejs.' 

```
!ENTRY org.eclipse.equinox.preferences 4 2 2014-07-23 22:52:07.621
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.preferences".
!STACK 0
java.lang.IllegalStateException: Could not find Node.js.
        at org.nodeclipse.ui.preferences.PreferenceInitializer.findNode(PreferenceInitializer.java:158)
        at org.nodeclipse.ui.preferences.PreferenceInitializer.initializeDefaultPreferences(PreferenceInitializer.java:92)
        at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper$1.run(PreferenceServiceRegistryHelper.java:300)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.runInitializer(PreferenceServiceRegistryHelper.java:303)
        at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.applyRuntimeDefaults(PreferenceServiceRegistryHelper.java:131)
        at org.eclipse.core.internal.preferences.PreferencesService.applyRuntimeDefaults(PreferencesService.java:368)
        at org.eclipse.core.internal.preferences.DefaultPreferences.applyRuntimeDefaults(DefaultPreferences.java:166)
        at org.eclipse.core.internal.preferences.DefaultPreferences.load(DefaultPreferences.java:237)
```

**Comment by paulvi** [comment]
Or better 

    sudo update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10
