### ISSUE TITLE
Nodeclipse 1.0: Failed to replace env in config: ${APPDATA}

### ISSUE THREAD

**Issue by paulvi** [Nodeclipse/nodeclipse-1#197]
when creating new Express Project with Nodeclipse 1.0

```
Error: Failed to replace env in config: ${APPDATA}
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:429:13
    at String.replace (native)
    at envReplace (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:424:12)
    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:400:7)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:338:17
    at Array.forEach (native)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:337:23)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:325:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16

Error: Failed to replace env in config: ${APPDATA}
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:429:13
    at String.replace (native)
    at envReplace (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:424:12)
    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:400:7)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:338:17
    at Array.forEach (native)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:337:23)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:325:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16

```

**Comment by paulvi** [comment]
ref https://github.com/npm/npm/issues/7468  
ref https://github.com/npm/npm/issues/2840

**Comment by paulvi** [comment]
related to #81 

now need to set `APPDATA`  (added to "PATH", "TEMP", "TMP", and "SystemDrive")
