### ISSUE TITLE
ArrayIndexOutOfBound for Node Application launchers with PreferenceConstants.NODE_PASS_ALL_ENVIRONMENT_VARIABLES disabled.

### ISSUE THREAD

**Issue by ThottChief** [Nodeclipse/nodeclipse-1#198]
Whenever I try to launch a .js file as a node application I get

```
java.lang.ArrayIndexOutOfBoundsException: 5
	at org.nodeclipse.debug.launch.LaunchConfigurationDelegate.getEnvironmentVariables(LaunchConfigurationDelegate.java:281)
	at org.nodeclipse.debug.launch.LaunchConfigurationDelegate.launch(LaunchConfigurationDelegate.java:221)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```
Happens to all normal node application launchers as well as debug launchers.

Nodeclipse version : 1.0.1.201509240713
Eclipse: 4.5.0

**Comment by ThottChief** [comment]
Could determine through Github the relevant code at
https://github.com/Nodeclipse/nodeclipse-1/blob/master/org.nodeclipse.debug/src/org/nodeclipse/debug/launch/LaunchConfigurationDelegate.java:257

Worked around it by simply enabling PreferenceConstants.NODE_PASS_ALL_ENVIRONMENT_VARIABLES aka "pass all environment variables of Eclipse to launched Node.js app" in preferences pane.

Didn't disable it on purpose maybe on accident. Seems to be a bug anyway so I leave this here changing the title appropriately.

**Comment by paulvi** [comment]
Thanks for raising.

Can you share code snippet enough to reproduce?

**Comment by paulvi** [comment]
OK, that is bug, because of https://github.com/Nodeclipse/nodeclipse-1/commit/c40583e52ecb3c163405f5f5a58213b749e0f146 was not tested

**Comment by paulvi** [comment]
Made a 1.0.2 release because of this.

It will be published today.
