### ISSUE TITLE
Error running Angular app

### ISSUE THREAD

**Issue by ddausch** [Nodeclipse/nodeclipse-1#200]
I have a pre-existing Angular app that I am trying to get running within the Nodeclipse env. I have been able to get simple non-angular test apps to run here but getting the following error when attempting to run the Angular app w/in Eclipse:

```
C:\MyProjects\git_repositories\sportal-ui\src\app\index.js:5
angular.module('sportalUi', ['ngAnimate', 'ngCookies', 'ngTouch', 'ngSan
^
ReferenceError: angular is not defined
    at Object.<anonymous> (C:\MyProjects\git_repositories\sportal-ui\src\app\index.js:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Is there a runtime config change I need to make?

**Comment by paulvi** [comment]
If you can run it from command line <kbd>Ctrl+ALt+D</kbd>,  it should run from within IDE as well.

No changes needed.

Can you share the code?

**Comment by JavaPantry** [comment]
I have the same error, but in wizard generated New 'Node.js Project'
Steps to reproduce:
- install Nodeclipse Core & Node.js (nodeclipse-1) from marketplace
- Generate new Node.js Project 'HelloNodeclipse'
- in project root folder run >bower install
- in project explorer right click over HelloNodeclipse/public/app.js and select Debug as NodeJs App


Debugger listening on port 5858
C:\spring-tool-suite-3.7.0_Workspace\HelloNodeclipse\public\app.js:2
var app = angular.module('MyAngularApp',[]);
          ^
ReferenceError: angular is not defined
    at Object.<anonymous> (C:\spring-tool-suite-3.7.0_Udemy_Workspace\HelloNodeclipse\public\app.js:2:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.runMain [as _onTimeout] (module.js:467:10)
    at Timer.listOnTimeout (timers.js:92:15)

I'm NodeJs beginner. ;)
Any advice?

**Comment by paulvi** [comment]
Please create new issue

**Comment by paulvi** [comment]
Closing as old
