### ISSUE TITLE
TODO check with Neon

### ISSUE THREAD

**Issue by paulvi** [Nodeclipse/nodeclipse-1#212]
When trying with Neon-javascript

got error when trying to debug

```
Debugger listening on port 5858
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write ECONNRESET
    at exports._errnoException (util.js:870:11)
    at Socket._writeGeneric (net.js:681:26)
    at Socket._write (net.js:700:8)
    at doWrite (_stream_writable.js:301:12)
    at clearBuffer (_stream_writable.js:404:7)
    at Socket.Writable.uncork (_stream_writable.js:238:7)
    at Client.send (_debug_agent.js:172:15)
    at Client.start (_debug_agent.js:176:8)
    at Agent.onConnection (_debug_agent.js:67:5)
    at emitOne (events.js:77:13)
```

Need more testing and feedback.

**Comment by paulvi** [comment]
It is Oxygen already
