### ISSUE TITLE
Error org/chromium/debug/core/model/LineBreakpointAdapter$ForVirtualProject

### ISSUE THREAD

**Issue by dPhantum** [Nodeclipse/nodeclipse-1#224]
When changing panes within the Eclipse IDE (clicking between them, project explorer to editor, etc), in my case specifically using PDT, an error dialog appears every time, this surmounts to hundreds of time per day for a heavy user of the system like myself.

The following is the dialog, the error log, and the process stack associated with the error log entries.
![eclipseerror](https://user-images.githubusercontent.com/33183843/38570163-d1ac3d2a-3cb2-11e8-89d7-8f3638728f15.png)
![errorgalore](https://user-images.githubusercontent.com/33183843/38570172-d793e15c-3cb2-11e8-807e-056f57dc19f6.png)

```
Java.lang.NoClassDefFoundError: org/chromium/debug/core/model/LineBreakpointAdapter$ForVirtualProject
	at org.chromium.debug.ui.ChromiumToggleBreakpointTargetFactory.isApplicable(ChromiumToggleBreakpointTargetFactory.java:43)
	at org.chromium.debug.ui.ChromiumToggleBreakpointTargetFactory.getToggleTargets(ChromiumToggleBreakpointTargetFactory.java:28)
	at org.eclipse.debug.internal.ui.actions.ToggleBreakpointsTargetManager$ToggleTargetFactory.getToggleTargets(ToggleBreakpointsTargetManager.java:241)
	at org.eclipse.debug.internal.ui.actions.ToggleBreakpointsTargetManager.getEnabledTargetIDs(ToggleBreakpointsTargetManager.java:521)
	at org.eclipse.debug.internal.ui.actions.ToggleBreakpointsTargetManager.getPreferredToggleBreakpointsTargetID(ToggleBreakpointsTargetManager.java:543)
	at org.eclipse.debug.internal.ui.actions.ToggleBreakpointsTargetManager.getToggleBreakpointsTarget(ToggleBreakpointsTargetManager.java:549)
	at org.eclipse.debug.internal.ui.actions.breakpoints.RetargetBreakpointAction.getAdapter(RetargetBreakpointAction.java:49)
	at org.eclipse.debug.internal.ui.actions.RetargetAction.selectionChanged(RetargetAction.java:151)
	at org.eclipse.debug.internal.ui.actions.breakpoints.RetargetBreakpointAction.selectionChanged(RetargetBreakpointAction.java:75)
	at org.eclipse.ui.internal.PluginAction.refreshEnablement(PluginAction.java:206)
	at org.eclipse.ui.internal.PluginAction.selectionChanged(PluginAction.java:273)
	at org.eclipse.ui.internal.PluginAction.selectionChanged(PluginAction.java:297)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:239)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.handleSelectionChanged(SelectionService.java:88)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$0(SelectionService.java:64)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$2.run(SelectionAggregator.java:126)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.notifyListeners(SelectionAggregator.java:123)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.access$6(SelectionAggregator.java:121)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$7$1.run(SelectionAggregator.java:231)
	at org.eclipse.e4.core.contexts.RunAndTrack.runExternalCode(RunAndTrack.java:56)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$7.changed(SelectionAggregator.java:228)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:114)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:355)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:370)
	at org.eclipse.e4.ui.internal.workbench.SelectionServiceImpl.setSelection(SelectionServiceImpl.java:31)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.selectionChanged(CompatibilityPart.java:461)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:155)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:152)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2180)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1223)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1252)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:240)
	at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:235)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by paulvi** [comment]
OK, thanks for stacktrace.

The code in question is `ChromiumToggleBreakpointTargetFactory.java:43` https://github.com/Nodeclipse/nodeclipse-1/blob/master/chromedevtools/plugins/org.chromium.debug.ui/src/org/chromium/debug/ui/ChromiumToggleBreakpointTargetFactory.java#L43
that  references `ForVirtualProject` static inner class
https://github.com/Nodeclipse/nodeclipse-1/blob/master/chromedevtools/plugins/org.chromium.debug.core/src/org/chromium/debug/core/model/LineBreakpointAdapter.java#L24

The code is 5 years old, and if it worked before in PDT Eclipse package (I bet it did),
so most likely something happen in Eclipse itself,  
or there is other Chromium version installed, that creates conflict.

@dPhantum Can you check your installed Cromium version in Help -> About Eclipse -> Details button

![image](https://user-images.githubusercontent.com/1614482/38624234-352d4434-3dda-11e8-9b4e-670aea4213af.png)

**Comment by dPhantum** [comment]
Sure thing, this is the info:
JavaScript Development Tools Chromium/V8 Remote Debugger	
0.6.0.v201705091354	
org.eclipse.wst.jsdt.chromium.debug.feature.feature.group	
Eclipse Web Tools Platform

**Comment by paulvi** [comment]
```
JavaScript Development Tools Chromium/V8 Remote Debugger
0.6.0.v201705091354
org.eclipse.wst.jsdt.chromium.debug.feature.feature.group
Eclipse Web Tools Platform
```
is not produced by @Nodeclipse but by Eclipse WTP project https://www.eclipse.org/webtools/ as it is clearly seen now.

File a bug at https://bugs.eclipse.org/bugs/,  
would be nice to reference from here and back from bugzilla.

**Comment by dPhantum** [comment]
Got it.
There is a bug posted at: https://bugs.eclipse.org/bugs/show_bug.cgi?id=533507

**Comment by paulvi** [comment]
Product/Component selection are wrong, should be WTP/something

Hopefully they can move it....

**Comment by paulvi** [comment]
http://eclip.se/533507
