### ISSUE TITLE
Node.js app with cluster does not execute inside Nodeclipse // Unknown system errno 203

### ISSUE THREAD

**Issue by paulvi** [Nodeclipse/nodeclipse-1#81]
This code with `cluster` usage does not execute inside Nodeclipse

``` javascript
    var cluster = require('cluster');
    var numCPUs = require('os').cpus().length;

    if (cluster.isMaster) {
        // Fork workers.
        for ( var i = 0; i < numCPUs; i++) {
            cluster.fork();
        }

        cluster.on('death', function(worker) {
            console.log('worker ' + worker.pid + ' died');
            cluster.fork();
        });
    }
```

It is finishing with 

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn Unknown system errno 203
    at errnoException (child_process.js:945:11)
    at Process.ChildProcess._handle.onexit (child_process.js:736:34)
```

Possibly output is less, because of #71

**Comment by Stelminator** [comment]
@palcocer I found this while trying to debug a nodejs cluster app, but your link is dead.  Any chance you could explain your workaround here?
